# cfg file with sim settings used to create V.O. dataset
SEED: 1

ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  TURN_ANGLE: 9 # CUSTOM (SMNet)
  FORWARD_STEP_SIZE: 0.1 # CUSTOM (SMNet)

  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 1.5 # CUSTOM (SMNet)
    RADIUS: 0.1 # CUSTOM (SMNet)
    
    # RADIUS: 0.18

  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
    
  RGB_SENSOR:
    
    # CUSTOM (SMNet)
    WIDTH: 640
    HEIGHT: 480
    HFOV: 90
    POSITION: [0, 1.25, 0]

    # DEFAULTS
    # WIDTH: 341
    # HEIGHT: 192
    # HFOV: 70
    # POSITION: [0, 0.88, 0]
    # NOISE_MODEL: "GaussianNoiseModel"
    # NOISE_MODEL_KWARGS:
    #   intensity_constant: 0.1

  DEPTH_SENSOR:
    # CUSTOM (SMNet)
    WIDTH: 640
    HEIGHT: 480
    HFOV: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    POSITION: [0, 1.25, 0]
    
    # DEFAULTS
    # WIDTH: 341
    # HEIGHT: 192
    # HFOV: 70
    # NOISE_MODEL: "RedwoodDepthNoiseModel"

  # DEFAULTS
  # ACTION_SPACE_CONFIG: 'pyrobotnoisy'
  # NOISE_MODEL:
  #   ROBOT: "LoCoBot"
  #   CONTROLLER: 'Proportional'
  #   NOISE_MULTIPLIER: 0.5
    
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.36 # 2 x Agent Radius

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', "SUCCESS", 'SPL', 'SOFT_SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2 # 2 x Agent Radius
    # SUCCESS_DISTANCE: 0.36 # 2 x Agent Radius

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  SCENES_DIR: dataset/ # CUSTOM (MP3D)
  DATA_PATH: dataset/habitat_datasets/pointnav/mp3d/v1/{split}/{split}.json.gz # CUSTOM (MP3D)
